# Generated by Django 3.0.4 on 2020-09-22 20:57

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='product',
            name='ci_res',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='cover'),
        ),
    ]
