# Generated by Django 3.0.4 on 2020-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
