# Generated by Django 3.0.4 on 2020-10-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20201020_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='free',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
